# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('casenum', models.IntegerField()),
                ('ordernum', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateField()),
                ('provider', models.CharField(max_length=50)),
                ('patient', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('expecteddate', models.DateField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
