# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='address',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
