# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0006_auto_20170724_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='teethnum',
        ),
    ]
