# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0008_case_teethnum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case',
            new_name='Order',
        ),
    ]
