# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0009_auto_20170724_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='casenum',
            field=models.IntegerField(verbose_name='Case No.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expecteddate',
            field=models.DateField(verbose_name='Expected Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateField(verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordernum',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Order No.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(choices=[('PFM High Noble', 'PFM High Noble'), ('PFM Semi Precious', 'PFM Semi Precious'), ('PFM Non Precious', 'PFM Non Precious'), ('Full Gold Crown', 'Full Gold Crown'), ('Full Cast Semi Precious', 'Full Cast Semi Precious'), ('Full Cast Non Precious', 'Full Cast Non Precious'), ('Crown Fit to Partial', 'Crown Fit to Partial'), ('Metal Occlusal', 'Metal Occlusal'), ('Metal Lingual', 'Metal Lingual'), ('Zirlux Temporary', 'Zirlux Temporary'), ('Cast Coping', 'Cast Coping'), ('PFM High Noble', 'PFM High Noble'), ('PFM Semi Precious', 'PFM Semi Precious'), ('PFM Bridges(Non Precious Alloy)', 'PFM Bridges(Non Precious Alloy)'), ('Emax Bridge', 'Emax Bridge'), ('Bruxzir Crown', 'Bruxzir Crown'), ('Zirconia Crown', 'Zirconia Crown'), ('Lava Crown', 'Lava Crown'), ('Emax Crown', 'Emax Crown'), ('Empress Crown', 'Empress Crown'), ('Zirconia Veneer', 'Zirconia Veneer'), ('Bruxzir Bridge 2', 'Bruxzir Bridge 2'), ('Bruxzir Bridge', 'Bruxzir Bridge'), ('Zirconia Bridge', 'Zirconia Bridge'), ('Lava Bridge', 'Lava Bridge'), ('Emax Bridge', 'Emax Bridge'), ('Empress Bridge', 'Empress Bridge'), ('Custom Abutment Anterior', 'Custom Abutment Anterior'), ('Custom Abutment Posterior', 'Custom Abutment Posterior'), ('Custom Zirconia Abutment Anterior', 'Custom Zirconia Abutment Anterior'), ('Custom Zirconia Abutment Posterior', 'Custom Zirconia Abutment Posterior'), ('Conus Abutment', 'Conus Abutment'), ('Hybrid Bar', 'Hybrid Bar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='teethnum',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32)], default=1, verbose_name='Tooth No.'),
        ),
    ]
