# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0011_auto_20170725_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.CharField(default='..', max_length=500),
        ),
    ]
