# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:36
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0015_auto_20170726_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='teethnum',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32)], max_length=86, verbose_name='Tooth No.'),
        ),
    ]
